---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  path: mono/src

steps:
- name: build
  image: spritsail/abuild:3.12
  pull: always
  settings:
    publickey: https://alpine.spritsail.io/spritsail-alpine.rsa.pub
    repo_sshfs: "drone-upload@web.spritsail.io:"
  environment:
    SIGNINGKEY:
      from_secret: signingkey
    SSHKEY:
      from_secret: sshkey
  privileged: true

...
